### ISSUE TITLE
Does sirmordred support adding argument like "--from-date" to collect data?

### ISSUE THREAD

**Issue by eyehwan** [chaoss/grimoirelab-sirmordred#505] opened 2021-05-22 14:40 UTC
In perceval, it is supported by adding "--from-date" to define the start timestamp, but in sirmodred I didn't find any similar definitions on the cfg file or cmd argument. 

Is this a supported feature in sirmordred?

**Comment by eyehwan** [comment] 2021-05-22 14:50
Find some hints through https://github.com/chaoss/grimoirelab-sirmordred/search?q=from-date&type=code. 
So "from-date" is a supported configs for all the data source, like github?

**Comment by vchrombie** [comment] 2021-05-22 16:37
Hi @eyehwan, yes you are right.

The `from-date` can be declared in the `setup.cfg` file and it is applied to all repositories of the data source.

Let us know if you need anything more.

**Comment by eyehwan** [comment] 2021-05-23 03:51
Unfortunately it is not working, I config it on git, github:pull github:issue, they always start fetching the data earlier than the date  I defined on the cfg.

```
[git]
raw_index = git_demo_raw
enriched_index = git_demo_enriched
latest-items = true
category = commit
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]
from-date = 2020-07-01

[github:issue]
raw_index = github_raw
enriched_index = github_enriched
api-token = ***********
category = issue
sleep-for-rate = true
no-archive = true
studies = [enrich_onion:github]
from-date = 2020-07-01

[github:pull]
raw_index = github-pull_raw
enriched_index = github-pull_enriched
api-token = ***********
category = pull_request
sleep-for-rate = true
no-archive = true
from-date = 2020-07-01
```
![image](https://user-images.githubusercontent.com/1535756/119247449-0eb63500-bbbc-11eb-90a3-de63c2c6796e.png)

![image](https://user-images.githubusercontent.com/1535756/119247454-255c8c00-bbbc-11eb-999d-70b57a04fe80.png)

![image](https://user-images.githubusercontent.com/1535756/119247458-33aaa800-bbbc-11eb-84f0-4b6776bf9dba.png)


grimoirelab 0.2.55
sirmordred 0.2.37

I install the whole solution through grimorelab:
./build_grimoirelab -l debug --logfile /root/tmp/log --build --install --check \
  --relfile ../releases/0.2.55 --reposdir /root/repos \
 --install_venv /root/venvs/mayfour

Could you tell me if I configured wrong, or is there any other ways to do so?

Thanks.

**Comment by vchrombie** [comment] 2021-05-24 06:16
Hi @eyehwan, thanks for reporting this.

> Unfortunately it is not working, I config it on git, github:pull github:issue, they always start fetching the data earlier than the date I defined on the cfg.

Did you happen to run grimoirelab previously before adding the `from-date`? I was thinking if there was some existing data already which is why you see it in the indexes. You can delete the indexes using the dev tools of Kibiter.

```
DELETE git_demo_raw
DELETE github_raw
DELETE github-pull_raw
```

If you have the enriched indexes, please delete them too. When everything is clean, you can try to extract data using the `from-date`.
 
> ![image](https://user-images.githubusercontent.com/1535756/119247454-255c8c00-bbbc-11eb-999d-70b57a04fe80.png)
> 
> ![image](https://user-images.githubusercontent.com/1535756/119247458-33aaa800-bbbc-11eb-84f0-4b6776bf9dba.png)

Also, I think you created the raw indexes (`github_raw` and `github-pull_raw`). You can check the enriched data in the enriched indexes (`github_enriched` and `github-pull_enriched`). This is not related in any way to the `from-date` issue though.

The raw indexes contain the raw data coming from perceval, the enriched data comes from ELK and it is showed in the dashboards and panels.

> grimoirelab 0.2.55
> sirmordred 0.2.37
> 
> I install the whole solution through grimorelab:
> ./build_grimoirelab -l debug --logfile /root/tmp/log --build --install --check
> --relfile ../releases/0.2.55 --reposdir /root/repos
> --install_venv /root/venvs/mayfour

Do you mind checking the [docker-compose solution](https://github.com/chaoss/grimoirelab/tree/master/docker-compose) of the grimoirelab. It is a quick solution without much hassle and configuration.

[Simplifying how to install GrimoireLab](https://chaoss.community/blog-post/2019/10/08/simplifying-how-to-install-grimoirelab/
)

Please let us know if you need any help.

**Comment by eyehwan** [comment] 2021-05-24 08:03
Hi @vchrombie , thanks for your help. 
> Did you happen to run grimoirelab previously before adding the from-date? I was thinking if there was some existing data already which is why you see it in the indexes. You can delete the indexes using the dev tools of Kibiter.

> Do you mind checking the docker-compose solution of the grimoirelab. It is a quick solution without much hassle and configuration.

Yes, I am using Elasticsearch, Kibana and mariadb run by docker-compose.
I totally remove the docker services by `docker-compose down --remove-orphans` before I retried again, to secure Elasticsearch doesn't exist any data before starting the  Grimoirelab.  
But it is still the same result, --from-data doesn't work for me :(

**Comment by zhquan** [comment] 2021-05-24 09:54
Hi @eyehwan  

Could you remove your index pattern and create them using these fields as `Time filter field name`?
- github_raw: `data.updated_at`
- github-pull_raw: `data.updated_at`
- git: `grimoire_creation_date`
- git_raw: `metadata__updated_on`

And you should see these logs on your `all.log` in your first execution:
- [git] Incremental from: 2020-07-01 00:00:00+00:00 for GIT-REPO
- [github] Incremental from: 2020-07-01 00:00:00+00:00 for GITHUB-REPO

Here an example the same raw GITHUB index but using a different time filter:
- `data.created_at`
![github_created_at](https://user-images.githubusercontent.com/5637233/119329075-1c83bd00-bc85-11eb-867d-f066952508e4.png)

- `data.updated_at`
![github_updated_at](https://user-images.githubusercontent.com/5637233/119329111-273e5200-bc85-11eb-8b84-025a22366a33.png)

GIT
- raw
![git_updated_on](https://user-images.githubusercontent.com/5637233/119330360-691bc800-bc86-11eb-9b74-bbe94998f0e6.png)

- enriched
![git_grimoire_creation_date](https://user-images.githubusercontent.com/5637233/119330376-6faa3f80-bc86-11eb-9f18-2230f8fe1696.png)

I hope it helps you.

Best,
Quan

**Comment by eyehwan** [comment] 2021-05-25 00:53
@zhquan 
Thanks a lot. 
I will take a try again and feedback later.

BR//Yehui.

**Comment by vchrombie** [comment] 2021-05-25 13:44
Great! Thanks for letting us know @eyehwan.

It would be great if you can close the issue as the problem is resolved.

**Closed** 2021-05-25 14:16 UTC
