### ISSUE TITLE
Error installing mordred

### ISSUE THREAD

**Issue by sulunemre** [chaoss/grimoirelab-sirmordred#172] opened 2018-07-05 10:14 UTC
Hi, I am following the guide: https://chaoss.github.io/grimoirelab-tutorial/before-you-start/installing-grimoirelab.html 

An error occures when typed `(grimoirelab) $ pip3 install grimoire-mordred`
It shows a long message. In the middle, it says
`Failed building wheel for dulwich`
and at the end:
`Command "/home/emresulun93/venvs/grimoirelab/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-
install-hu_ieezp/dulwich/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n'
);f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-6gh_7yc7/install-record.txt -
-single-version-externally-managed --compile --install-headers /home/emresulun93/venvs/grimoirelab/include/site/p
ython3.5/dulwich" failed with error code 1 in /tmp/pip-install-hu_ieezp/dulwich/`

Python 3.6 is installed on the system and I tried to create the virtual environment with Python 3.5 instead of 3.6 but got the same error. Also, the same error occurred while installing the perceval.

**Comment by jgbarah** [comment] 2018-07-05 10:55
Thanks for your report. Something weird is happening, because you say you're using Python3.6, but the log you post says `/home/emresulun93/venvs/grimoirelab/bin/python3.5`, which means in the virtual environment you're using Python3.5 for some reason.

However, the error does not seem to be related to that. It could be a problem compiling C extensions. To check if that's the issue, please run:

```
pip3 install dulwich --global-option="--pure"
```

within the virtual environment before running again

```
pip3 install grimoire-mordred
```

And let us know the results, please.

(see the rationale for this in the [Installation doc for dulwich](https://www.dulwich.io/docs/#installation).

**Comment by sulunemre** [comment] 2018-07-05 20:39
Note that if you want to reproduce the issue,

- Go to Google Cloud compute engine.

- Create a [new virtual machine](https://console.cloud.google.com/launcher/details/debian-cloud/debian-stretch) with Debian.

- And follow the [guide](https://chaoss.github.io/grimoirelab-tutorial/before-you-start/installing-grimoirelab.html).

Thanks

**Comment by jgbarah** [comment] 2018-07-05 21:23
> Didn't work, I got the same error.

Just to be sure, what you did is:

```
python3 -m venv ~/venvs/grimoirelab
source ~/venvs/grimoirelab/bin/activate
pip3 install --upgrade pip
pip3 install --upgrade setuptools
pip3 install --upgrade wheel 
pip3 install dulwich --global-option="--pure"
pip3 install grimoire-mordred
```

And you got the same error as above, about `Failed building wheel for dulwich`?

**Comment by sulunemre** [comment] 2018-07-06 19:37
Yes, here is the full log: https://gist.github.com/sulunemre/d4d97b81a5d15135b6f6bd7f6abb7d1c

**Comment by jgbarah** [comment] 2018-07-08 22:30
Thanks for the log. From it, it seems that `--pure` works for installing dulwich, but it fails with some other package. So, let's try some other approach. I've been looking around, and maybe you are experiencing dulwich/dulwich/#242. I've reproduced it in a Debian container, with a very similar output to yours. If that's the case, you could try to install `python3-dev` Debian packge:

```
sudo apt-get install python3-dev
```

And then try once again with 

```
pip3 install grimoire-mordred
```

(in the same virtual environment that you already had).

Please, let us know if this works, or the log of how it fails, otherwise...

**Comment by jgbarah** [comment] 2018-07-10 22:42
OK, i see. It seems you have a very bare Debian vm... The first log is failing because you don't have a compiler (gcc). So, let's assume the host is really bare... Try to run it this way, which is how I run it to produce the grimoirelab/factory container image, which builds on debian/stretch-slim, which is also very bare (see [Dockerfile](https://github.com/chaoss/grimoirelab/blob/master/docker/Dockerfile-factory) for details, if you want).

```
sudo apt-get update
sudo apt-get -y install bash locales gcc git git-core pandoc mariadb-client python3-venv python3-dev
```

(maybe you don't need all of that, but it cannot make harm...)

And now try again installing GrimoireLab:

```
python3 -m venv ~/venvs/grimoirelab
source ~/venvs/grimoirelab/bin/activate
pip3 install --upgrade pip setuptools wheel 
pip3 install grimoire-mordred
```

And again, please let me know what happens...

**Comment by sulunemre** [comment] 2018-07-11 05:08
It works very well, thank you for your generous support. Also loved the product.

**Comment by jgbarah** [comment] 2018-07-11 22:02
Great!!

Thanks for your kind comments. Please, close this issue if you feel we're done, then.

**Closed** 2018-07-12 05:07 UTC
