### ISSUE TITLE
predictable or random task order

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/grimoirelab-sirmordred#346] opened 2019-10-08 20:05 UTC
I received the following question via email:

When mordred creates arthurd/arthurw tasks, will it always go in the same order or does it try to randomize the tasks order?

**Comment by valeriocos** [comment] 2019-10-08 20:15
it is better if you redirect the person to the issue tracker. It avoids you to be in the middle.

**Comment by GeorgLink** [comment] 2019-10-08 20:37
Good thinking. 😁
I posted the issue and directed the person here.

**Comment by lukaszgryglicki** [comment] 2019-10-09 05:57
Great, I just wanted to know that but decided to ask instead of creating an issue or feature request.

**Comment by valeriocos** [comment] 2019-10-09 08:17
No worries @lukaszgryglicki!

> When mordred creates arthurd/arthurw tasks, will it always go in the same order or does it try to randomize the tasks order?

The initial order is always the same. Once the tasks are in Arthur:
- if there is only one worker, the order will be always the same. In particular, once the task is finished, it enters again in the queue and it will be processed by the same worker.
- if there are more workers, the order will probably change, since it depends on the task execution time. In particular, tasks with shorter execution time will enter again in the queue before tasks with longer execution times.

Does the answer solve your question?

**Comment by lukaszgryglicki** [comment] 2019-10-09 09:30
Yes, thanks. I was only wondering if there is (or there is not) some random, shuffle of tasks "array" before passing them to arthur.

**Comment by valeriocos** [comment] 2019-10-09 09:58
We don't introduce any random shuffling, however it is possible that when loading the repositories from the projects.json, the order of the repositories change. I'm checking the code to confirm.

In case it is confirmed, would you like to keep the order consistent across the different executions?

**Comment by lukaszgryglicki** [comment] 2019-10-09 11:25
I just wanted to know, randomizing or not, just curious. We just had some issues and when we redeployed `mordred` pods it sometimes helped sometimes not, but possibly having > 1 `arthur` workers can explain that there was a "race" between them (not in any bad meaning) which result was just random-like execution order so sometimes wrong repositories/data sources got into execution sooner than later.

**Comment by valeriocos** [comment] 2019-10-10 11:14
Fixed with #351

**Closed** 2019-10-10 11:14 UTC
